<a href="https://colab.research.google.com/github/anuragrahate29/pythonLibraries/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import sys

Why Numpy is faster than list ? : The list in the memory stores four types of data namely Size of list(4 Bytes), reference Count(8 bytes),Object Type and Obj Value(8 bytes each), thus increasing the amt of data to retreive.While numpy stores using only 4 bytes. Also Contiguos memory location usage in numpy. Also no type conversion in numpy compared to List.

In [15]:
a = np.array([1,2,3] , dtype='int32')
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [8]:
# Get Dimension
a.ndim

1

In [9]:
b.ndim

2

In [10]:
a.shape

(3,)

In [11]:
b.shape

(2, 3)

In [16]:
# To get the datatype
a.dtype

dtype('int32')

In [18]:
# to get size
a.itemsize

4

In [19]:
b.itemsize #Since it is float

8

In [20]:
a.nbytes

12

In [22]:
b.nbytes

48

# Accessing/Changing specific elements , rows, columns


In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [26]:
a[1,5]

13

In [28]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [29]:
a[:,3]

array([ 4, 11])

In [30]:
# Getting a little more fancy to retreive [startindex:endindex:stepsize]
a[0,1:6:2] #a[row num, startindex:endindex:stepsize ]

array([2, 4, 6])

In [32]:
a[1,5] = 20
print(a)

#a[:,2] = 5
a[:,2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [33]:
#3-d Example
b = np.array([[[1,2],[3,4]],[[5,6],[6,7]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [6 7]]]


In [34]:
#To get specific element : work outisde in
b[0,1,1]

4

In [43]:
b[1,0,0] = 5
print(b)

[[[33  2]
  [ 9 20]]

 [[ 5  6]
  [ 8 20]]]


# Initializing Different types of Array

In [45]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [46]:
np.ones((4,2,2),dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [47]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [48]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [50]:
#Random Decimal numbers
np.random.rand(4,2)

array([[0.51101202, 0.58749941],
       [0.86832602, 0.15673516],
       [0.92866365, 0.17591362],
       [0.65967589, 0.81088496]])

In [54]:
#Random Integer Values
np.random.randint(44, size = (3,3))

array([[40, 15, 30],
       [ 3,  8, 29],
       [40, 10, 26]])

In [55]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 0)
print(r1)
#axis=0 means repeat the entire row along the rows.

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [7]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 1)
print(r1)
#axis=1 means repeat elements along the columns.

[[1 1 1 2 2 2 3 3 3]]


In [13]:
op = np.ones((5,5))
print(op)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

op[1:4,1:4] = z
print(op)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [19]:
# Copying matrix
# a = np.array([1,2,3])
# b = a
# b[0] = 100
# print(b)

In [17]:
# print(a)
# It can be seen the changes in b also affects a , they are basically
# referencing to the same memory location

[100   2   3]


In [18]:
# To make the changes in b not reflect in a , the copy. of the
# respective matrix , then
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [20]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [21]:
a + 2

array([3, 4, 5, 6])

In [22]:
a - 2

array([-1,  0,  1,  2])

In [23]:
a * 2

array([2, 4, 6, 8])

In [24]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [25]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [26]:
a ** 2

array([ 1,  4,  9, 16])

In [28]:
print(np.cos(a))

[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]


# Linear Algebra


In [29]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [34]:
# Find the determinant :We know that determinant of identity matrix is 1
c = np.identity(3)
print(c)
np.linalg.det(c)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

In [35]:
c = np.eye(3, 4)  # Creates a 3x4 matrix with 1s on the main diagonal
print(c)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


# Statistics

In [36]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.min(stats,axis = 1) # axis=1 looks row wise comparing them with
# columns of that row

array([1, 4])

In [40]:
np.min(stats,axis = 0) # axis=0 looks columns wise minimum ranging
# columns from 0 - 2

array([1, 2, 3])

# Reorganizing Array

In [5]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)


[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# Horizontal stack
h1 = np.ones((2,5))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0.]])

In [8]:
# Miscellaneous

In [ ]:
filedata = np.genfromtxt('file.txt',delimiter=',')
filedata = filedata.astype('int32')
filedata

In [ ]:
filedata > 50 # gets the true of false based on condition

In [9]:
# We can index with a lsit in numPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
np.all(filedata > 50, axis = 0) # axis=0 is to check in row
#return false if atleast one value is less than 50 in the row

In [ ]:
np.any(filedata > 50, axis = 1) # axis=0 is to check in column
#return true if atleast one value is less than 50 in the column